# Generated by Django 5.1.3 on 2024-11-22 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='typeshop/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PU', 'Pune'), ('MU', 'Mumbai'), ('NA', 'Nagpur'), ('KO', 'Kokan'), ('SA', 'Satara')], default='PU', max_length=9)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Shop Variety',
                'verbose_name_plural': 'Shop Varieties',
            },
        ),
    ]
